openapi: 3.0.0
info:
  title: Intercompany Treasury API
  version: 1.0.0
  description: Enterprise-grade API for intercompany transfers and balances
servers:
  - url: http://localhost:4001/api
paths:
  /transfers:
    get:
      summary: List all intercompany transfers
      responses:
        '200':
          description: List of transfers
    post:
      summary: Create a new intercompany transfer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IntercompanyTransferInput'
      responses:
        '200':
          description: Created transfer
  /balances:
    get:
      summary: List all intercompany balances
      responses:
        '200':
          description: List of balances
  /audit:
    get:
      summary: List audit log entries
      responses:
        '200':
          description: List of audit logs
components:
  schemas:
    IntercompanyTransferInput:
      type: object
      properties:
        fromEntity:
          type: string
        toEntity:
          type: string
        amount:
          type: number
        currency:
          type: string
        reference:
          type: string
        meta:
          type: object
      required:
        - fromEntity
        - toEntity
        - amount
        - currency
