import { defineConfig } from 'vitest/config';
import { resolve } from 'path';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    coverage: {
      provider: 'c8',
      reporter: ['text', 'lcov', 'html'],
      exclude: [
        'node_modules/',
        'dist/',
        'coverage/',
        '**/*.test.ts',
        '**/*.spec.ts',
        '**/__tests__/**',
        '**/__mocks__/**',
        'scripts/',
        'config/',
        'examples/',
      ],
    },
    include: ['**/*.test.ts', '**/*.spec.ts', '**/__tests__/**/*.ts'],
    exclude: ['node_modules/', 'dist/', 'coverage/', '**/*.d.ts'],
  },
  resolve: {
    alias: {
      '@': resolve(__dirname, './'),
      '@types': resolve(__dirname, './types'),
      '@lib': resolve(__dirname, './lib'),
      '@utils': resolve(__dirname, './utils'),
      '@validation': resolve(__dirname, './validation'),
      '@metadata': resolve(__dirname, './types/metadata'),
      '@config': resolve(__dirname, './config'),
      '@examples': resolve(__dirname, './examples'),
      '@ai': resolve(__dirname, './ai/src'),
      '@cli': resolve(__dirname, './cli/src'),
      '@collaboration': resolve(__dirname, './collaboration/src'),
      '@compliance': resolve(__dirname, './compliance/src'),
      '@debugging': resolve(__dirname, './debugging/src'),
      '@monitoring': resolve(__dirname, './monitoring/src'),
      '@ui-components': resolve(__dirname, './ui-components/src'),
      '@vscode-extension': resolve(__dirname, './vscode-extension/src'),
      '@components': resolve(__dirname, './ui-components/src'),
      '@hooks': resolve(__dirname, './ui-components/src/hooks'),
      '@primitives': resolve(__dirname, './ui-components/src/primitives'),
      '@theme': resolve(__dirname, './ui-components/src/theme'),
      '@analytics': resolve(__dirname, './ui-components/src/analytics'),
      '@data': resolve(__dirname, './ui-components/src/data'),
      '@forms': resolve(__dirname, './ui-components/src/forms'),
      '@layout': resolve(__dirname, './ui-components/src/layout'),
      '@performance': resolve(__dirname, './ui-components/src/performance'),
      '@search': resolve(__dirname, './ui-components/src/search'),
      '@feedback': resolve(__dirname, './ui-components/src/feedback'),
      '@job-queue': resolve(__dirname, './ui-components/src/job-queue'),
    },
  },
});
